/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  IncomeCategories: () => import('#controllers/income_categories_controller'),
}
