/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Contacts: () => import('#controllers/contacts_controller'),
  ExpenseCategories: () => import('#controllers/expense_categories_controller'),
  Expenses: () => import('#controllers/expenses_controller'),
  IncomeCategories: () => import('#controllers/income_categories_controller'),
  Incomes: () => import('#controllers/incomes_controller'),
  InternalTransfers: () => import('#controllers/internal_transfers_controller'),
  TransactionAnalytics: () => import('#controllers/transaction_analytics_controller'),
  WalletAnalytics: () => import('#controllers/wallet_analytics_controller'),
  WalletTypes: () => import('#controllers/wallet_types_controller'),
  Wallets: () => import('#controllers/wallets_controller'),
}
