/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type IncomeCategoryTransformer from '#transformers/income_category_transformer'
import type IncomeTransformer from '#transformers/income_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type WalletTransformer from '#transformers/wallet_transformer'
import type WalletTypeTransformer from '#transformers/wallet_type_transformer'
import type ContactTransformer from '#transformers/contact_transformer'

export namespace Data {
  export type IncomeCategory = InferData<IncomeCategoryTransformer>
  export namespace IncomeCategory {
    export type Variants = InferVariants<IncomeCategoryTransformer>
  }
  export type Income = InferData<IncomeTransformer>
  export namespace Income {
    export type Variants = InferVariants<IncomeTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type Wallet = InferData<WalletTransformer>
  export namespace Wallet {
    export type Variants = InferVariants<WalletTransformer>
  }
  export type WalletType = InferData<WalletTypeTransformer>
  export namespace WalletType {
    export type Variants = InferVariants<WalletTypeTransformer>
  }
  export type Contact = InferData<ContactTransformer>
  export namespace Contact {
    export type Variants = InferVariants<ContactTransformer>
  }
}
