/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContactSchema extends BaseModel {
  static $columns = ['color', 'comments', 'createdAt', 'email', 'id', 'image', 'name', 'phoneNumber', 'type', 'updatedAt', 'userId'] as const
  $columns = ContactSchema.$columns
  @column()
  declare color: string
  @column()
  declare comments: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string | null
  @column()
  declare name: string
  @column()
  declare phoneNumber: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class IncomeCategorySchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'defaultContactId', 'defaultWalletTypeId', 'icon', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = IncomeCategorySchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare defaultContactId: number | null
  @column()
  declare defaultWalletTypeId: number | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class IncomeSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'date', 'description', 'fromContactId', 'id', 'incomeCategoryId', 'name', 'updatedAt', 'userId', 'walletId'] as const
  $columns = IncomeSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column()
  declare description: string
  @column()
  declare fromContactId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare incomeCategoryId: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare walletId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'email', 'emailVerificationCode', 'emailVerificationCodeExpiresAt', 'emailVerified', 'emailVerifiedAt', 'firstName', 'id', 'lastName', 'password', 'resetPasswordToken', 'resetPasswordTokenExpiresAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare emailVerificationCode: string | null
  @column.dateTime()
  declare emailVerificationCodeExpiresAt: DateTime | null
  @column()
  declare emailVerified: boolean
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare resetPasswordToken: string | null
  @column.dateTime()
  declare resetPasswordTokenExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WalletTypeSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'icon', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = WalletTypeSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class WalletSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'description', 'id', 'image', 'name', 'updatedAt', 'userId', 'walletTypeId'] as const
  $columns = WalletSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare walletTypeId: number
}
